import assert from "node:assert/strict"
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { afterEach, test } from "node:test"
import { syncInventory } from "../inventory.ts"

const originalFetch = globalThis.fetch
afterEach(() => { globalThis.fetch = originalFetch })

test("generates a V2 provider model overlay and retains it on discovery failure", async () => {
  const home = await mkdtemp(join(tmpdir(), "knowit-gateway-"))
  try {
    await mkdir(join(home, "opencode"))
    globalThis.fetch = async () => Response.json({ data: [{ id: "vendor/coder", name: "Coder" }] })
    assert.equal(await syncInventory(home, "test-key", "https://example.test/v1"), 1)
    const content = await readFile(join(home, "opencode", "opencode.jsonc"), "utf8")
    assert.match(content, /Generated by knowit-ai-gateway/)
    assert.deepEqual(JSON.parse(content.replace(/^\/\/[^\n]*\n/, "")), {
      providers: { "knowit-ai-gateway": { models: { "vendor/coder": { name: "Coder" } } } },
    })
    assert.ok(!content.includes("test-key"))

    globalThis.fetch = async () => new Response(null, { status: 503 })
    assert.equal(await syncInventory(home, "test-key", "https://example.test/v1"), 1)
    assert.equal(await readFile(join(home, "opencode", "opencode.jsonc"), "utf8"), content)
  } finally {
    await rm(home, { recursive: true, force: true })
  }
})

test("does not overwrite an unrelated config file", async () => {
  const home = await mkdtemp(join(tmpdir(), "knowit-gateway-"))
  try {
    await mkdir(join(home, "opencode"))
    await writeFile(join(home, "opencode", "opencode.jsonc"), "{}")
    await assert.rejects(syncInventory(home, "test-key"), /not managed/)
  } finally {
    await rm(home, { recursive: true, force: true })
  }
})
