import { readFile, rename, unlink, writeFile } from "node:fs/promises"
import { join } from "node:path"
import { discoverModels } from "./models.ts"

const marker = "// Generated by knowit-ai-gateway; do not edit.\n"
const baseURL = "https://ai.aiservices.knowit.no/v1"

export async function syncInventory(configHome: string, apiKey: string, endpoint = baseURL): Promise<number> {
  if (!apiKey) throw new Error("AGW_API_KEY is missing from the server environment")
  const path = join(configHome, "opencode", "opencode.jsonc")
  const existing = await readFile(path, "utf8").catch((error: NodeJS.ErrnoException) => {
    if (error.code === "ENOENT") return undefined
    throw error
  })
  if (existing !== undefined && !existing.startsWith(marker)) {
    throw new Error(`${path} already exists and is not managed by knowit-ai-gateway`)
  }

  let models
  try {
    models = await discoverModels(endpoint, apiKey, AbortSignal.timeout(10_000))
  } catch (error) {
    if (existing === undefined) throw error
    console.warn(`knowit-ai-gateway: discovery failed; using the last generated model list (${String(error)})`)
    return Object.keys(JSON.parse(existing.slice(marker.length)).providers["knowit-ai-gateway"].models).length
  }

  const content = marker + JSON.stringify({
      providers: {
        "knowit-ai-gateway": {
          models: Object.fromEntries(models.map(({ id, name }) => [id, { name }])),
        },
      },
    }, null, 2) + "\n"
  if (content === existing) return models.length

  const temporary = `${path}.${process.pid}.tmp`
  try {
    await writeFile(temporary, content, { mode: 0o600 })
    await rename(temporary, path)
  } finally {
    await unlink(temporary).catch((error: NodeJS.ErrnoException) => {
      if (error.code !== "ENOENT") throw error
    })
  }
  return models.length
}
